#ifndef __TILE_TYPE_H_DEFINED__
#define __TILE_TYPE_H_DEFINED__

// enum containing the type of a tile for later comparisons
enum TileType
{
	STEELPLANKS, 
	PATCHBOT_SPAWN,
	ENEMY_SPAWN,
	ABYSS,
	WATER,
	ROOT_SERVER,
	ALIEN_GRASS,
	GRAVEL,
	SECRET_ENTRANCE,
	MANUAL_DOOR,
	AUTO_DOOR,
	INDESTRUCTABLE_WALL,
	DESTRUCTABLE_WALL
};

#endif